
def logo():
  print(" \n             mm               ")
  print("           B@P@BXBM:           ") 
  print("         .u@B@B@B@Bi           ")  
  print("       GB@B@MBMBB@kr0.         ")
  print("      :@B@MBB@B@B@B@B@B:       ")
  print("   .:j@B@Fi   7r  .iXB@@U:,    ")
  print(".LO@B@uY7vrLZOOM8Ovr7vL2B@BMu  ")
  print("@ZJL@     ,,:BZq@i:,     BYJBB ")
  print("i:@ B,   .B@BM  G@B@.   .@ 0uk ")
  print("8.5v@B,   1@@.  .B@1   .BB7JrB ")
  print("B@E@BBM8qZu:      :200EMM@BOB8 ")
  print("  ::@BBB              @B@B::   ")
  print("    :@B@O            GB@Bi       ===================================================    ")
  print("      XB@q .@@@B@B1 1@@X    ===========.......Gracias por usar 'Cerrajero'.......===========") 
  print("        Y@Br     .i@BU           =====================  Buen dia. ==================")
  print("         .@B@BBM@@@B.          ")
  print("            .7Yjr.             ")

def logo_cerrajero():
  print(" \n                :i:      ")
  print("               u@@@@@@@v    ")
  print("             P@@@OL7jB@@@L  ")
  print("            O@@2       8@@Y ")
  print("           .@@k         @@@ ")
  print("           7@@.         L@@ ")
  print("            @@N         @@@ ")
  print("            E@@X       @@@r ")
  print("           0@@@@@@X20@@@@i  ")
  print("         Y@@@@@B@@@@@@@7    ")
  print("       ,@@@@@@i             ")
  print("      Z@@@@@F         ===================================================     ")
  print("    v@@@@@q     ===========.......Hello world, I am Cerrajero.....=================    ")
  print("  ,@@@@@@@              ===================================================    ")
  print(" O@@@@@@@@@@.               ")
  print("F@@@@B@@@  \@,               ")
  print(" 8@@r  8@,                  \n ")
  print("E                 \n ")

def logo_cerrajeroEND():
  print(" \n                :i:      ")
  print("               u@@@@@@@v    ")
  print("             P@@@OL7jB@@@L  ")
  print("            O@@2       8@@Y ")
  print("           .@@k         @@@ ")
  print("           7@@.         L@@ ")
  print("            @@N         @@@ ")
  print("            E@@X       @@@r ")
  print("           0@@-J-@X20@@@@i  ")
  print("         Y@@-U-B@@@@@@@7    ")
  print("       ,@@-N-@i             ")
  print("      Z@-G-@F         ===================================================     ")
  print("    v@-L-@q     ===========.......Gracias por usar 'Cerrajero'.......===========    ")
  print("  ,@-A-@@@              =================== Buen dia ! ======================    ")
  print(" O@@-C-@@@@@.               ")
  print("F@-O-@@@  \@,               ")
  print(" D-@r  8@,                  ")
  print("E                 \n ")